### ISSUE TITLE
Windows wont let me open the porter.

### ISSUE THREAD

**Issue by GeoIsTimeless** [gusborg88/fnf-porter#10]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the preset selected?

Charts only

### What are the contents of the latest .log file? (if applicable)

Cant even open the porter

### What are the contents of your mod folder? (if applicable)

None so far.

### Additional Context (if applicable)

Everytime I try to open up the porter, Windows gives me the access denied notification.
![image](https://github.com/gusborg88/fnf-porter/assets/90113724/f5953b24-6925-4187-b86e-9574ab289b42)

**Comment by gusborg88** [comment]
did you extract it or does that pop up when you try to?
Maybe run as administrator

**Comment by GeoIsTimeless** [comment]
> did you extract it or does that pop up when you try to? Maybe run as administrator

I tried to extract it but it still gives me the error.

**Comment by GeoIsTimeless** [comment]
> did you extract it or does that pop up when you try to? Maybe run as administrator

**Comment by GeoIsTimeless** [comment]
Never mind, I had to turn off my anti virus.
