### ISSUE TITLE
The porter can't open.

### ISSUE THREAD

**Issue by GeoIsTimeless** [gusborg88/fnf-porter#11]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the preset selected?

Charts only

### Additional Context (if applicable)

I figured out the solution to the last issue and now I have returned to make another suggestion becuase an error message keeps popping up.
![image](https://github.com/gusborg88/fnf-porter/assets/90113724/dfa7acc6-b37f-443c-8a52-bed3a1cd62ce)

**Comment by GeoIsTimeless** [comment]
Nevermind. Had to extract it.

**Comment by tposejank** [comment]
Sometimes life be like that
