### ISSUE TITLE
Scrolling to mod week causes crash.

### ISSUE THREAD

**Issue by VocalFan** [gusborg88/fnf-porter#15]
### Issue Checklist

- [X] I have properly named the issue
- [x] I looked in issues/discussions, if my question was previously anwsered

### What is the preset selected?

Full mod

### What are the contents of the latest .log file? (if applicable)

![image](https://github.com/gusborg88/fnf-porter/assets/45863583/de2a60c7-9f64-41ad-8ab2-2b12e36ee373)
![image](https://github.com/gusborg88/fnf-porter/assets/45863583/669fd602-22fe-451b-b6bb-930fcafa59f8)
[crash-2024-05-23-02-35-17.log](https://github.com/gusborg88/fnf-porter/files/15412730/crash-2024-05-23-02-35-17.log)

### Additional Context (if applicable)

This was with the Psych engine version of the CG5 week, works fully in Psych engine, but when converted to FNF with the tool, I first get this error on load:

![image](https://github.com/gusborg88/fnf-porter/assets/45863583/0d8336c9-bce3-497d-98b1-ee11281db73f)

But it continues to the menus, which if I try to scroll to the CG5 week... Errors above.

Selecting songs in Freeplay works.

**Comment by gusborg88** [comment]
yeah there are some known issues with weeks. Theres a new pr that might've fixed it (idk i havent tested it), maybe try that?

**Comment by VocalFan** [comment]
> yeah there are some known issues with weeks. Theres a new pr that might've fixed it (idk i havent tested it), maybe try that?

Chief, I made that PR-

**Comment by OyasumiGalaxy** [comment]
I didn't see this when i was looking sorry
though it does show its still happening
