### ISSUE TITLE
Vocal Split fails to generate files.

### ISSUE THREAD

**Issue by VocalFan** [gusborg88/fnf-porter#17]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the preset selected?

Charts only

### Additional Context (if applicable)

Vocal Split option is ticked, and when used, seems to remove the Voices.ogg from the song's folder, but doesn't add the split vocals into the folder, leaving only the inst.ogg, which leads to the song having no vocals at all. Sad times.

**Comment by tposejank** [comment]
There are a lot of checks in the songs part. Some may not be activating this time, if possible could you share the contents of the folder the vocal split was supposed to act on? And please check you have FFMPEG on your machine
