### ISSUE TITLE
Potentially add modname to end of character files

### ISSUE THREAD

**Issue by VocalFan** [gusborg88/fnf-porter#19]
### What category does this fall into?

File conversion

### Additional Context (if applicable)

To make it where mods don't cross over and bug out eachother, maybe make every character file include the modname at the end...

Like:

BF-CG5Psych.json
BF-Updike.json
BF-HazyRiver.json

That way mods don't cross over each other all trying to use their custom BF.

**Comment by BombasticTom** [comment]
Don't really understand what you're thinking of, could you explain more in detail?

**Comment by VocalFan** [comment]
> Don't really understand what you're thinking of, could you explain more in detail?

Instead of mods going hrr durr and having bf.json that conflict with each other (usually 1 bf overrides them all... I think it's the last mod folder loaded that gets the override?)

Maybe just put the modname at the end of all the mod's specific characters. (Should also prevent gf from spazzing out in base game)

**Comment by VocalFan** [comment]
![image](https://github.com/gusborg88/fnf-porter/assets/45863583/e453a27a-a50b-4d33-b7cb-61d20a3f31d1)

As you can see... It still uses the Updike BF (going off the icon there), and the broken train GF. Even in base game.

**Comment by BombasticTom** [comment]
Ohhh I see
We'll make a fix for it!

**Comment by gusborg88** [comment]
i think this is a base game issue unfortunately, once a mod is in the mods folder its always loaded. Its not like Psych Engine where you can enable and disable specific mods.
If we did rename the jsons for each mod it also might not be recognized by the songs. Sorry but we cant fix this

**Comment by BombasticTom** [comment]
best advice is to wait for a mod manager update to the base game, which they're probably going to release soon

**Comment by BombasticTom** [comment]
(im pretty sure someone already made a mod manager though)
