### ISSUE TITLE
Mac build cannot start

### ISSUE THREAD

**Issue by fnfmodding** [gusborg88/fnf-porter#20]
### Issue Checklist

- [X] I have properly named the issue
- [ ] I looked in issues/discussions, if my question was previously anwsered

### What is the preset selected?

Full mod

### Additional Context (if applicable)

Mac build cannot be started.
Binary is not executable.
I tried the command chmod in the terminal to make the binary executable, but it didn't make it executable.

**Comment by BombasticTom** [comment]
I don't think we have mac testers for our tool, so that's why this went over our heads. I'll talk more about this once the whole team is active again

**Comment by fnfmodding** [comment]
> I don't think we have mac testers for our tool, so that's why this went over our heads. I'll talk more about this once the whole team is active again
