### ISSUE TITLE
Add a check for empty folders

### ISSUE THREAD

**Issue by Rev2-Git** [gusborg88/fnf-porter#26]
### What category does this fall into?

Asset copying

### Additional Context (if applicable)

The application closes and ends conversion if an empty or invalid data folder is found. Maybe add a check for that, so it skips over data it can’t copy instead of trying to use empty folders.

**Comment by BombasticTom** [comment]
okay ate some food development continues!

**Comment by BombasticTom** [comment]
Should be fixed, @Rev2-Git please check if it doesn't crash now (download the [latest action build](https://github.com/gusborg88/fnf-porter/actions/runs/9211085423))
