### ISSUE TITLE
Some mods have extra notes lying on top of the normal notes

### ISSUE THREAD

**Issue by Willio2000** [gusborg88/fnf-porter#32]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the preset selected?

Charts only

### What is missing?

nothing is missing. 

### Missing files checklist

- [X] I have checked the converter supports these files
- [ ] I have checked both directories, the original and converted one, and they aren't in the converted one

### Additional Context (if applicable)

When the program came to chart the song
, it put in extra notes that lie on top of the normal chart so you miss when playing the song. an example is with the mod biden blast. somewhere in the middle of the song there was extra notes that caused me to miss. those were a pain to take out because you cant really see where they are in the editor because they are on top of each other. I had to tell using the player hitsound. anyway, yeah theres the extra notes in the chart that you cant see ooooo scary spooky
_anyway here's biden blast chart if you want it_
[biden-blast-chart.json](https://github.com/gusborg88/fnf-porter/files/15418397/biden-blast-chart.json)
[biden-blast-metadata.json](https://github.com/gusborg88/fnf-porter/files/15418399/biden-blast-metadata.json)

**Comment by VocalFan** [comment]
This should be fixed.

Basically, the notes are in the Psych engine chart, but Psych Engine 'hides' them in gameplay. I added it so those notes are removed in conversion as base engine doesn't hide dupe notes lol
