### ISSUE TITLE
Move from OS to Pathlib

### ISSUE THREAD

**Issue by BombasticTom** [gusborg88/fnf-porter#34]
### What category does this fall into?

Asset copying

### Additional Context (if applicable)

Fixes a lot of security concerns, as suggested by [@METGameDev](https://x.com/metgamedev/status/1793648726927679666)

**Comment by VocalFan** [comment]
@BombasticTom I can try at this.

**Comment by BombasticTom** [comment]
Sure, make a pull request once you're done

**Comment by tposejank** [comment]
In PR #36

**Comment by gusborg88** [comment]
im working on this rn
Also check this out https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module

**Comment by VocalFan** [comment]
Uh... Again, PR-

**Comment by VocalFan** [comment]
Gotta check the issues before you assign them xD

**Comment by gusborg88** [comment]
mb i didnt notice
