### ISSUE TITLE
Trying to Convert this 3 Things it crashes (Stages, Images, Pack Meta)

### ISSUE THREAD

**Issue by MemTheBun** [gusborg88/fnf-porter#39]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the preset selected?

Full mod

### What are the contents of the latest .log file? (if applicable)

14:20:06: [log.py:50] [INFO] Logger initialized!
14:20:06: [window.py:451] [INFO] Initiating window
14:20:35: [window.py:69] [INFO] Thanks for using FNF Porter!

### What are the contents of your mod folder? (if applicable)

[pack.json](https://github.com/gusborg88/fnf-porter/files/15422784/pack.json)
[memsterstage.json](https://github.com/gusborg88/fnf-porter/files/15422787/memsterstage.json)

**Comment by tposejank** [comment]
![image](https://github.com/gusborg88/fnf-porter/assets/81495861/04a8696c-ebf6-471d-bf42-bed2b9284b3e)
![image](https://github.com/gusborg88/fnf-porter/assets/81495861/b7de67c5-cb25-4e3a-ba2f-29872af66dee)
These files have invalid .json format. They fail upon loading up.

**Comment by MemTheBun** [comment]
my stupid ass... im sorry!
