### ISSUE TITLE
it's not letting open it

### ISSUE THREAD

**Issue by coolguy9191** [gusborg88/fnf-porter#40]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I looked in issues/discussions, if my question was previously anwsered

### What is the preset selected?

I chose

### Additional Context (if applicable)

I just downloaded the porter and my laptop won't even open it

**Comment by gusborg88** [comment]
what platform?

**Comment by tposejank** [comment]
closed bc no response + known issue too
