### ISSUE TITLE
Icons not loading for some characters

### ISSUE THREAD

**Issue by gusborg88** [gusborg88/fnf-porter#6]
for example, turnip 17bucks the icon is just the haxe logo
Psych engine character json says `"healthicon": "nip",` 
base game character json says
```
"healthIcon": {
        "id": "nip",
        "isPixel": false,
        "flipX": false,
        "scale": 1
    },
```
the image in both cases is called icon-nip.png

Works on some characters but not others

**Comment by VocalFan** [comment]
![image](https://github.com/gusborg88/fnf-porter/assets/45863583/bf588d94-e7b7-4b9b-9672-71046894e651)
Happens for Tone-It-Down on Hazy River.

**Comment by QuagisCool** [comment]
Your icons are probably the wrong size, i would try and open an icon like boyfriend in an art program, pasting the icons you want over, and saving them as the character you wants icon

**Comment by VocalFan** [comment]
> Your icons are probably the wrong size, i would try and open an icon like boyfriend in an art program, pasting the icons you want over, and saving them as the character you wants icon

Nah, this was mainly as naming issue. Lilrascal's icon file was called lilrascal.png instead of icon-lilrascal
